
== Overview

These tests try to call mpi4py on a subcommunicator created by a C program.

Ultimately, the goal is to
. Run arbitrary mpi4py codes in-memory from Swift/T
. Run Horovod in-memory from Swift/T

The C-Python stuff is in py.c, copied from
https://github.com/ECP-CANDLE/Supervisor/tree/master/scratch/py-eval

== Setup

Edit setup.sh:

. Set SPACK
. Set HASH locations for each package

(Could have used 'spack load' but this is more fundamental.)

== Run

The test scripts automatically source +setup.sh+ and run +make+ as necessary.

Simply run the test number you want:

----
$ ./test-1.sh # or 2..6
# or
$ ./test-all.sh
----

== Test summary

test-1:: (C&#8203;) Plain use of py.c

test-2:: (C&#8203;) Use of mpi4py from py.c .  Requires mpi4py built from
source, so use Spack for Python and mpi4py and MPI.

test-3:: (C,Python) Use of constructed communicator in mpi4py

test-4:: (Swift) Plain use of python()

test-5:: (Swift) 'import mpi4py' from Swift/T

test-6:: (Swift) Use of constructed communicator from Swift
