#!/bin/bash
set -eu

crash()
{
  echo "report:" ${*}
  exit 1
}

if (( ${#} != 1 ))
then
  crash "provide DIR"
fi
DIR=$1

if ! [[ -d $DIR ]]
then
  crash "no directory: $DIR"
fi
if ! [[ -f $DIR/jobid.txt ]]
then
  crash "no jobid file: $DIR"
fi

head -c 7                       $DIR/jobid.txt
echo
grep "PROCS\|NODES\|PPN"        $DIR/turbine.log
grep "TURBINE_WORKERS"          $DIR/turbine.log
grep "ADLB_SERVERS"             $DIR/turbine.log
if ! grep "TASKS:"              $DIR/output.txt
then
  crash "job not started: $DIR"
fi
if ! grep "EXIT CODE:"          $DIR/output.txt
then
  crash "job not complete: $DIR"
fi
grep "COMPLETED:"               $DIR/output.txt
grep "ADLB Total Elapsed Time:" $DIR/output.txt
