#!/bin/bash
set -eu

# Presume success:
CODE=0

crash()
{
  echo "report:" ${*}
  exit 1
}

if-grep()
# Handle grep not-found cases
# Sets CODE=1 but does not crash script
{
  if grep "${@}"
  then
    : OK
  else
    local PATTERN="$1"
    shift
    echo "pattern '$PATTERN' not found in ${*}"
    # Global CODE
    CODE=1
  fi
}

if (( ${#} != 1 ))
then
  crash "provide DIR"
fi
DIR=$1

if ! [[ -d $DIR ]]
then
  crash "no directory: $DIR"
fi
if ! [[ -f $DIR/jobid.txt ]]
then
  crash "no jobid file: $DIR"
fi

echo -n "JOB:                "
# Cut out Aurora junk from ID:
head -c 7                $DIR/jobid.txt
echo
# Want NODES at top for readability
grep "NODES"             $DIR/turbine.log
grep "PROCS\|PPN"        $DIR/turbine.log
grep "TURBINE_WORKERS"   $DIR/turbine.log
grep "ADLB_SERVERS"      $DIR/turbine.log
if-grep "TASKS:"         $DIR/output.txt
if ! grep "EXIT CODE:"   $DIR/output.txt
then
  crash "job not complete: $DIR"
fi
if-grep "COMPLETED:"               $DIR/output.txt
if-grep "ADLB Total Elapsed Time:" $DIR/output.txt

if (( CODE != 0 ))
then
  grep "died" $DIR/output.txt
  echo "ERROR!"
fi
exit $CODE
