#!/bin/bash
set -eu

# RUN
# $ ./run PROCS PPN OUTPUT
# PPN should normally be 12

if (( ${#} != 3 ))
then
  echo "run: provide PROCS PPN OUTPUT"
  exit 1
fi
PROCS=$1
export PPN=$2
export TURBINE_OUTPUT_ROOT=$3

# See https://docs.alcf.anl.gov/aurora/running-jobs-aurora/#submitting-a-job
export TURBINE_DIRECTIVE="#PBS -l filesystems=flare"

# Defaults:
: ${PROJECT:=candle_aesp_CNDA} ${QUEUE:=debug-scaling} ${ADLB_SERVERS:=1}
export PROJECT QUEUE ADLB_PRINT_TIME=1

SWIFT=/lus/flare/projects/workflow_scaling/sfw/swift-t/2025-06-05-perf
PATH=$SWIFT/stc/bin:$PATH

export THIS=$( cd $( dirname $0 ) ; /bin/pwd )

TASKS=$[ (PROCS - ADLB_SERVERS) * 10 ]

set -x
which swift-t
swift-t -m pbs -n $PROCS $THIS/workflow.swift -n=$TASKS
