
= File append examples

== File index

original.swift:: The original example provided by Heldenbrand

a0.swift:: The original example with a minor file name change to make it runnable by all
+
----
$ swift-t a0.swift
$ cat example.txt
line1
line2
----

a-sh.swift:: A working example of file append by calling the shell with a Swift app function
+
----
$ swift-t a-sh.swift
appending 'line2' to example.txt
$ cat example.txt
line1
line2
----

a-sh.sh:: Supporting shell script for a-sh.swift

a-tcl.swift:: A working example of file append without a shell script by using Tcl code (could use Python, etc., here too)
+
----
$ swift-t a-tcl.swift
$ cat example.txt
line1
line2
----
+
* local_file_path is the Tcl implementation of Swift's filename() - it extracts the filename from the file variable
* Tcl exec launches the rest of the line in the shell.  Thus, this is simply the same operation (echo s >> f) as in a-sh.sh

a-seek.swift:: A working example of record-oriented file append by using Tcl code (could use Python, etc., here too)
+
----
$ swift-t -p a-seek.swift -n=4
$ cat example.txt
line1
record 2 : line2
record 3 : line3
record 4 : line4
----

== Notes

Since Swift tasks run concurrently, there could be conflicting accesses at the end of a file when using the append file access mode (fopen(..., "a")).  Also, the order is non-deterministic, which could cause complexities.  Thus, the a-seek.swift example shows how to use an easily calculated offset to give non-conflicting accesses to different parts of the file.

In a-seek.swift, the file is opened, then the file descriptor fd is immediately seeked to position to kilobyte i.  Then a normal puts (print) statement writes the string "line"+i at that position.  The resulting file example.txt is thus sparse (cf. od -c example.txt).
