#!/bin/bash

# Test for Swift/T in E4S installation on Summit

module load e4s/20.10 stc/0.8.3
module list
which swift-t
export PROJECT=MED106      # <- Put your project here
export WALLTIME=00:05:00
export PPN=2               # Put 2 processes on one node
# Works currently:
# Prints 42 using a basic Swift/T function:
swift-t -m lsf -n 2 -E 'trace(42);'
# Will work if Python is enabled at Turbine configure time:
# Prints string "42" as generated by a Python snippet:
swift-t -m lsf -n 2 -i python -E 'trace(python("", "repr(42)"));'
# Success reports: "trace: 42"
# Failure reports: "Turbine not compiled with Python support"
